version: '2'

volumes:
  camsdata:

services:
  db_cams:
    image: cams:db
    volumes:
        - camsdata:/var/lib/postgresql/data
    environment:
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_USER=cams
        - POSTGRES_PASSWORD=camspass
  cams:
    image: cams:app
    ports:
      - "8000:8000"
    volumes:
        - /home/demonizer/projects/security/cams:/root/cams
    environment:
        - DB_USER=cams
        - DB_PASSWORD=camspass
        - DB_HOST=db_cams