version: '2'

volumes:
  redisdata:

services:
  redis:
    image: redis:4.0.9
    volumes:
      - 'redisdata:/data'
  cams:
    image: cams:app
    ports:
      - "8000:8000"
      - "3000:3000"
      - "8080:8080"
    volumes:
        - /home/demonizer/projects/security/cams:/root/cams
    environment:
      - REDIST_HOST=redis
    links:
      - redis